version: '3.8'

services:
  backend:
    build:
      context: ./rto-platform
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./rto-platform:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend2
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
